backend:
  branch: develop # Branch to update (optional; defaults to master)
  cms_label_prefix: netlify-cms/
  name: git-gateway
media_folder: assets/images
local_backend: true
public_folder: images
logo_url: https://next.madebykind.com/img/logo.svg
# publish_mode: editorial_workflow
site_url: https://next.madebykind.com/
collections:
  
  - name: 'blog'
    editor:
      preview: false
    label: 'Insights'
    label_singular: 'Insight'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { 
          label: 'Card colour', 
          name: 'card_colour', 
          widget: 'select',
          hint: 'This will be the card colours when no card image is selected. If an image is chosen it will overlay this.',
          default: { label: 'Blue on teal', value: 'bg-teal text-blue' },
          options: [
            { label: 'Dark green on sky blue', value: 'bg-sky text-green' },
            { label: 'Blue on light pink', value: 'bg-pink text-blue' },
            { label: 'Blue on teal', value: 'bg-teal text-blue' },
            { label: 'Blue on yellow', value: 'bg-yellow text-blue' },
          ]
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'select', required: false,
          options: [
            { label: 'Jess', value: 'jess' },
            { label: 'Mat', value: 'mat' },
            { label: 'Michelle', value: 'michelle' },
            { label: 'Pam', value: 'pam' },
            { label: 'Seth', value: 'seth' },
          ]
        }
      - { label: 'Illustration', hint: 'Optionally set an illustration as the card background. Always overriden by image.', name: 'illustration', widget: 'image', required: false, choose_url: false }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false, choose_url: false }
      - { 
          label: 'Text colour', 
          name: 'text_colour', 
          widget: 'select',
          required: false,
          hint: 'If an image is chosen you can set the text colour.',
          options: [
            { label: 'Buff', value: 'text-buff' },
            { label: 'White', value: 'text-white' },
          ]
        }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Services', name: 'services', widget: 'select', multiple: true, options: ['brand', 'digital', 'strategy'], required: false }
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - { label: 'Table of contents', name: 'toc', hint: 'Display links to section headings', widget: 'boolean', default: false, required: false }
      - { label: 'Featured', name: 'featured', hint: 'Featured posts display as a large card on the blog listing', widget: 'boolean', default: false, required: false }
      - { label: 'Summary', hint: 'This text shown on listing pages, possibly elsewhere! ¯\_(ツ)_/¯', name: 'summary', widget: 'string', required: false, hidden: true }
      - { label: 'Key Topic', name: 'key_topic', widget: 'string', required: false }
      - { label: 'Topics', name: 'topics', widget: 'list', required: false }
      - { label: 'Introduction', name: 'intro', widget: 'string', hint: 'This is large subtext that appears in the page header. It’s optional.', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'bold',
            'italic',
            'bulleted-list',
            'numbered-list',
            'quote',
            'code',
            'link',
          ]
        }
      - { label: 'Related pages', name: 'related_pages', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, required: false, valueField: '{{slug}}' }
      - { label: 'Related posts', name: 'related_posts', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, required: false, valueField: '{{slug}}' }
        
  - name: 'pages'
    editor:
      preview: false
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/pages'
    create: true
    delete: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false, choose_url: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'bulleted-list',
            'numbered-list'
          ]
        }

  - name: 'services'
    label: 'Services'
    label_singular: 'Service'
    editor:
      preview: false
    folder: 'content/services'
    create: true
    nested: { depth: 100 }
    delete: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false, choose_url: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Meta description', required: false, name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          required: false,
          hint: 'Main content goes here.',
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'bulleted-list',
            'numbered-list'
          ]
        }
      - { label: 'Related work', required: false, name: 'related_work', widget: 'relation', collection: 'work', searchFields: ['title'], multiple: true, valueField: '{{slug}}'}
      - { label: 'Related posts', required: false, name: 'related_posts', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, valueField: '{{slug}}'}
  
  - name: 'stats'
    label: 'Stats'
    label_singular: 'Fun fact…'
    folder: 'content/stats'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'string', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Stat description goes here.',
        }

  - name: 'testimonials'
    label: 'Testimonials'
    label_singular: 'Fab quote!'
    folder: 'content/testimonials'
    create: true
    editor:
      preview: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author image', name: 'image', widget: 'image', required: false }
      - { label: 'Role', hint: ' Who dis?! ¯\_(ツ)_/¯', name: 'role', widget: 'string', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Quote content goes here.',
        }
  
  - name: 'projects'
    label: 'Project summaries'
    label_singular: 'Project summary'
    folder: 'content/projects'
    create: true
    editor:
      preview: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string', hint: 'You can use Markdown for styling' }
      - { label: 'Images', name: 'image', widget: 'image', required: false, allow_multiple: true, choose_url: false }
      - { label: 'Topics', name: 'topics', widget: 'list', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Project summary content goes here.',
        }

  - name: 'work'
    editor:
      preview: false
    label: 'Case studies'
    label_singular: 'Case study'
    folder: 'content/work'
    create: true
    slug: '{{slug}}'
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false, choose_url: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Introduction', name: 'intro', widget: 'string', hint: 'This is large subtext that appears in the page header. It’s optional.', required: false }
      - { label: 'Key stat', hint: 'This is the headline statistic shown on the page header.', name: 'key_stat', widget: 'relation', collection: 'stats', searchFields: ['title'], multiple: false, required: false, valueField: '{{slug}}'}
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - { label: 'Summary', hint: 'This text shown on listing pages, possibly elsewhere! ¯\_(ツ)_/¯', name: 'summary', widget: 'string', required: false, hidden: true }
      - { label: 'Feature heading', name: 'feature_heading', widget: 'string', hint: 'This is heading of the big blue box.', required: false }
      - { label: 'Feature content', name: 'feature_content', widget: 'string', hint: 'This is content of the big blue box.', required: false }
      - { label: 'Services', name: 'services', widget: 'select', multiple: true, options: ['brand', 'digital', 'strategy'] }
      - { label: 'Topics', name: 'topics', widget: 'list', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'bold',
            'italic',
            'bulleted-list',
            'numbered-list',
            'quote',
            'code',
            'link',
          ]
        }