backend:
  branch: develop # Branch to update (optional; defaults to master)
  cms_label_prefix: netlify-cms/
  name: git-gateway
media_folder: assets/images
local_backend: true
public_folder: images
logo_url: https://next.madebykind.com/img/logo.svg
publish_mode: editorial_workflow
site_url: https://next.madebykind.com/
collections:
  
  - name: 'blog'
    editor:
      preview: false
    label: 'Blog'
    label_singular: 'Blog post'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Services', name: 'services', widget: 'select', multiple: true, options: ['brand', 'digital', 'strategy'], required: false }
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - { label: 'Summary', hint: ' This text shown on listing pages, possibly elsewhere! ¯\_(ツ)_/¯', name: 'summary', widget: 'string', required: false }
      - { label: 'Key Topic', name: 'key_topic', widget: 'string', required: false }
      - { label: 'Topics', name: 'topics', widget: 'list', default: ['User-centered design', 'Strategic consultancy', 'Digital sustainability'], required: false }
      - { label: 'Introduction', name: 'intro', widget: 'string', hint: 'This is large subtext that appears in the page header. It’s optional.', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'bold',
            'italic',
            'bulleted-list',
            'numbered-list',
            'quote',
            'code',
            'link',
          ]
        }
      - { label: 'Related pages', name: 'related_pages', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, required: false, valueField: 'title'}
      - { label: 'Related posts', name: 'related_posts', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, required: false, valueField: 'title'}
        
  - name: 'pages'
    editor:
      preview: false
    label: 'Pages'
    folder: 'content'
    create: false
    delete: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'bulleted-list',
            'numbered-list'
          ]
        }

  - name: 'services'
    label: 'Services'
    label_singular: 'New service'
    editor:
      preview: false
    folder: 'content/services'
    create: true
    delete: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'bulleted-list',
            'numbered-list'
          ]
        }
      - { label: 'Related pages', name: 'related_pages', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, valueField: 'title'}
      - { label: 'Related posts', name: 'related_posts', widget: 'relation', collection: 'blog', searchFields: ['title'], multiple: true, valueField: 'title'}
  
  - name: 'stats'
    label: 'Stats'
    label_singular: 'Fun fact…'
    folder: 'content/stats'
    create: true
    editor:
      preview: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'string', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Stat description goes here.',
        }

  - name: 'testimonials'
    label: 'Testimonials'
    label_singular: 'Fab quote!'
    folder: 'content/testimonials'
    create: true
    editor:
      preview: false
    filter:  
      field: 'hidden' 
      value: false
    fields:
      - { label: 'hidden', name: 'hidden', widget: 'hidden', default: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author image', name: 'image', widget: 'image', required: false }
      - { label: 'Role', hint: ' Who dis?! ¯\_(ツ)_/¯', name: 'role', widget: 'string', required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Quote content goes here.',
        }
  
  - name: 'work'
    editor:
      preview: false
    label: 'Case studies'
    label_singular: 'Case study'
    folder: 'content/work'
    create: true
    slug: '{{slug}}'
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'cover_img', widget: 'image', required: false }
      - { label: 'Alt text', name: 'cover_img_alt', widget: 'string', hint: 'Alt(ernative) text should describe the visual content of the image. Don’t start with “Image of…”!', required: false }
      - { label: 'Introduction', name: 'intro', widget: 'string', hint: 'This is large subtext that appears in the page header. It’s optional.', required: false }
      - { label: 'Meta description', name: 'description', widget: 'string', hint: 'This is the description of the page that is read by search engines. SEO innit?' }
      - { label: 'Summary', hint: ' This text shown on listing pages, possibly elsewhere! ¯\_(ツ)_/¯', name: 'summary', widget: 'string', required: false }
      - { label: 'Services', name: 'services', widget: 'select', multiple: true, options: ['brand', 'digital', 'strategy'] }
      - { label: 'Topics', name: 'topics', widget: 'list', default: ['User-centered design', 'Strategic consultancy', 'Digital sustainability'], required: false }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          hint: 'Main content goes here.',
          buttons: [
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'bold',
            'italic',
            'bulleted-list',
            'numbered-list',
            'quote',
            'code',
            'link',
          ]
        }