## Basic Configuration
baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Kind"
disableHugoGeneratorInject = true
author = "Future Friendly Ltd."
copyright = "Future Friendly Ltd."
canonifyURLs = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = false
summarylength = 10
paginate = 6
ignoreErrors           = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[build]
  publishResources = true
  #writeStats = true

[imaging]
  anchor = "smart"
  filter = "Lanczos"
  quality = 90

[imaging.exif]
  excludeFields = ".*"
  disableDate = true
  disableLatLong = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true

[module]

[[module.mounts]]
  source = "images"
  target = "src/images"

## Site Settings
[params]
  author = "Seth Warburton"
  date_format = "January 2, 2006"
  description = "Fast, secure, and accessible by default."
  email = "hello@madebykind.com"
  images = ["site-feature-image.jpg"]
  phone = "+441157270990"
  phonePretty = "0115 727 0990"
  since = 2009

  #github = "https://github.com/madebykind"
  linkedin = "https://www.linkedin.com/company/madebykind/"
  #twitter = "https://twitter.com/madebykind"
  #facebook = "https://facebook.com/madebykind"
  instagram = "https://instagram.com/imadebykind"

  # Table of contents
  toc = "tocbot"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[related]
  includeNewer = true
  toLower = true
  [[related.indices]]   
    name = "topics"
    weight = 100
  [[related.indices]]
    name = "services"
    weight = 10 

[services]
  [services.twitter]
    disableInlineCSS = true

[taxonomies]
  key_topic = "key_topic"
  rss = "rss"
  services = "services"
  topic = "topics"