## Basic Configuration
baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Inspired!"
disableHugoGeneratorInject = true
author = "Seth Warburton"
copyright = "All rights, and lefts, reserved."
canonifyURLs = true
enableGitInfo = true
# disqusShortname = "nternetinspired"
# googleAnalytics = "UA-XXXXX-Y"
enableRobotsTXT = true
summarylength = 10
paginate = 6

[build]
  publishResources = true
  writeStats = true

# Options for the Hugo deploy command
[deployment]

# [[deployment.targets]]
#   name = "example.com"
#   URL = "s3://[S3_BUCKET_NAME]?region=eu-west-2"
#   # If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
#   cloudFrontDistributionID =	"[CLOUDFRONT_DIST_ID]"

# # Behaviour and caching policies for specific file types
# [[deployment.matchers]]
#   # Cache static assets for 20 years.
#   pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
#   cacheControl = "max-age=630720000, no-transform, public"
#   gzip = true

[imaging]
  anchor = "smart"
  quality = 80

[imaging.exif]
  excludeFields = ".*"
  disableDate = true
  disableLatLong = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true

[module]

[[module.mounts]]
  source = "images"
  target = "src/images"

## Site Settings
[params]
  author = "Seth Warburton"
  date_format = "January 2, 2006"
  description = "Blazing fast, super secure and accessible by default"
  email = "hello@madebykind.com"
  images = ["site-feature-image.jpg"]
  naked = false
  owner = "Kind"
  phone = "+441157270990"
  phonePretty = "0115 727 0990"
  since = 2009

  # All dem socials
  #github = "https://github.com/nternetinspired"
  linkedin = "https://www.linkedin.com/in/ux-design-pro/"
  twitter = "https://twitter.com/nternetinspired"
  #facebook = "https://facebook.com/nternetinspired"
  instagram = "https://instagram.com/internetinspired"

  # Table of contents
  #toc = none, "hugo", or "tocbot"
  toc = "tocbot"

[params.clients]
  enable = true
  items = ["clients"]

[params.comments]
  enable = false

[params.features]
  enable = true
  items = ["features"]

[params.pricing]
  enable = true

[params.recent_posts]
  enable = true
  items = ["posts"]

[params.stats]
  enable = true
  items = ["stats"]

[params.testimonials]
  enable = true
  items = ["testimonials"]

[params.webmentions]
  enable = true
  username = "madebykind"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services]
  [services.twitter]
    disableInlineCSS = true

[taxonomies]
  rss = "rss"
  tag = "tags"