## Basic Configuration
baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Future Friendly Ltd."
disableHugoGeneratorInject = true
author = "Seth Warburton"
copyright = "All rights, and lefts, reserved, for ever!"
canonifyURLs = true
enableGitInfo = true
enableRobotsTXT = true
summarylength = 10
paginate = 6

[build]
  publishResources = true
  #writeStats = true

[imaging]
  anchor = "smart"
  quality = 80

[imaging.exif]
  excludeFields = ".*"
  disableDate = true
  disableLatLong = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true

[module]

[[module.mounts]]
  source = "images"
  target = "src/images"

## Site Settings
[params]
  author = "Seth Warburton"
  date_format = "January 2, 2006"
  description = "Blazing fast, super secure and accessible by default"
  email = "hello@madebykind.com"
  images = ["site-feature-image.jpg"]
  naked = false
  owner = "Kind"
  phone = "+441157270990"
  phonePretty = "0115 727 0990"
  since = 2009

  # All dem socials
  #github = "https://github.com/nternetinspired"
  linkedin = "https://www.linkedin.com/in/ux-design-pro/"
  twitter = "https://twitter.com/nternetinspired"
  #facebook = "https://facebook.com/nternetinspired"
  instagram = "https://instagram.com/internetinspired"

  # Table of contents
  toc = "tocbot"

[params.clients]
  enable = true
  items = ["clients"]

[params.comments]
  enable = false

[params.features]
  enable = true
  items = ["features"]

[params.recent_posts]
  enable = true
  items = ["posts"]

#[params.stats]
#  enable = true
#  items = ["stats"]

[params.testimonials]
  enable = true
  items = ["testimonials"]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services]
  [services.twitter]
    disableInlineCSS = true

[taxonomies]
  rss = "rss"
  tag = "tags"